### ISSUE TITLE
Reintroduce pipe seperator

### ISSUE THREAD

**Issue by RyanRoberts** [helloswish/craft-faceted-navigation#3]
While working with your plugin I noticed there's no way to add more than one category from a group, although there is in the original Craft 2 plugin. The original uses the | character.

e.g. /resources/types/**documents|posters**/

It looks like lines 68, 72 and 75 in Navigation.php (your plugin) have been changed from the original plugin (lines 42 and 46). I don't fully understand the changes you've made but I tried replacing them with the old plugin code and it brings back the ability to add more than one category in a group using the pipe in the URL.

Any chance you could look into officially reintroducing this feature? :) 

Thanks

**Comment by chadcrowell** [comment]
Hi again - I can get that fixed up for you this week sometime. I can't recall why I would have made that change, other than I was as newbie as could be to craft plugins when I ported this over, so I probably did that just to get it working for myself without understanding the implication of changing it.

**Comment by RyanRoberts** [comment]
That would be great if you could.

I'd do a pull request with changes but like you at the time I'm a newbie to plugins and PHP. 

Thanks!

**Comment by chadcrowell** [comment]
This has been fixed with [v1.1.0](https://github.com/helloswish/craft-faceted-navigation/releases/tag/1.1.0)

**Comment by chadcrowell** [comment]
I took some time today also and added a setting for the plugin in the Control Panel to enable or disable the multiple filtering capability per site.

**Comment by RyanRoberts** [comment]
Brilliant, thanks for the update.
