### ISSUE TITLE
Nested categories

### ISSUE THREAD

**Issue by markxxv** [helloswish/craft-faceted-navigation#4]
Hey there!

Is there any way to show nesting in categories in the filter?

Right now this example return absolutely flat filter list:
```
{% for categoryGroup in navItems.categoryGroups %}
    {% for category in attribute(
        navItems.categories, categoryGroup.handle
    ) %}
...
```

**Comment by chadcrowell** [comment]
Hi Mark, as noted in the read me, this plugin will only work with category groups that use 1 level of categories. Sorry I can't help you with nested lists.
