### ISSUE TITLE
Custom Category Fields

### ISSUE THREAD

**Issue by ambidustrious** [helloswish/craft-faceted-navigation#5]
Hello - Is it possible to access custom category fields?

I'm attempting to create a "toggle" on certain categories to hide them from the navigation.  Is there a better way?

Thanks

**Comment by chadcrowell** [comment]
Hi there - you can disable categories in Craft, which will hide them from the nav, but, of course, that completely stops them from showing or working site-wide, so I don't think that is what you want. 

If you added a lightswitch or similar field as a custom category field, that should work like so:

```
{% for categoryGroup in navItems.categoryGroups %}
	<h3>{{ categoryGroup.name }}</h5>
	<ul>
		{% for category in attribute(
			navItems.categories, categoryGroup.handle
			) where category.myCustomField == true %}
			<li{% if category.active %} class="active"{% endif %}>
				<a href="{{ url('inventory'~category.url.add) }}" class="add">{{ category.title}}</a>
				{% if category.active %} <a href="{{ url('inventory'~category.url.remove) }}" class="remove" title="Remove this filter">Remove</a> {% endif %}
			</li>
		{% endfor %}
	</ul>
{% endfor %}
```

The new code being `where category.myCustomField == true`

I have not tested this but give it a try and let me know if that doesn't do it for you.

**Comment by ambidustrious** [comment]
Thanks - Funny.... That's EXACTLY what I tried. It's doesn't seem to like the where clause on that query.

Here's the error
Unexpected token "name" of value "where" ("end of statement block" expected).

And my markup
                    {% for categoryGroup in navItems.categoryGroups %}
                        <h3>{{ categoryGroup.name }}</h5>
                        <ul class="catlist">
                            {% for category in attribute(
                                navItems.categories, categoryGroup.handle
                                )where category.highlight == true %}
                                <li{% if category.active %} class="active"{% endif %}>
                                    <a href="{{ url('products'~category.url.add) }}" class="add">{{ category.title}}</a>
                                    {% if category.active %} <a href="{{ url('products'~category.url.remove) }}" class="remove" title="Remove this filter"><i class="fa fa-minus-circle"></i></a> {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endfor %}

**Comment by ambidustrious** [comment]
Made a little progress with the query.. but I just don't seem to have access to custom fields. 

Key "highlight" for array with keys "attributes, title, active, url, model" does not exist.

**Attributes only has...**
groupId, newParentId, deletedWithGroup, id, tempId, draftId, revisionId, uid, siteSettingsId, fieldLayoutId, structureId, contentId, enabled, archived, siteId, title, slug, uri, dateCreated, dateUpdated, dateDeleted, root, lft, rgt, level, trashed, ref, status, url

**Comment by ambidustrious** [comment]
Ok - Here was my solution... not sure if this is the best approach, but it works...

		{% for category in attribute(
			navItems.categories, categoryGroup.handle
			)if category.model.behaviors.customFields.highlight  %}
			<li{% if category.active %} class="active"{% endif %}>
				<a href="{{ url('products'~category.url.add) }}" class="add">{{ category.title}}</a>
				{% if category.active %} <a href="{{ url('products'~category.url.remove) }}" class="remove" title="Remove this filter"><i class="fa fa-minus-circle"></i></a> {% endif %}
			</li>
		{% endfor %}

**Comment by chadcrowell** [comment]
It seems that is likely the best solution... there's nothing wrong with diving into the model to grab/eval a variable, so this would likely have been the next thing I recommended. If you find this is giving you trouble, then you may be stuck doing something like:

```
{% for categoryGroup in navItems.categoryGroups %}
	<h3>{{ categoryGroup.name }}</h5>
	<ul>
		{% for category in attribute(
			navItems.categories, categoryGroup.handle
			) %}
                        {% if category.highlight %}
			<li{% if category.active %} class="active"{% endif %}>
				<a href="{{ url('inventory'~category.url.add) }}" class="add">{{ category.title}}</a>
				{% if category.active %} <a href="{{ url('inventory'~category.url.remove) }}" class="remove" title="Remove this filter">Remove</a> {% endif %}
			</li>
                        {% endif %}
		{% endfor %}
	</ul>
{% endfor %}
```
